"""
Django settings for softeng project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

# Not remove the imports
from softeng.config import (
    PRODUCTION_APPS, DEVELOPMENT_APPS,
    PRODUCTION_DB, DEVELOPMENT_DB,
    STATIC_ROOT, STATIC_URL, MEDIA_ROOT, MEDIA_URL,
    LANGUAGE_CODE, TIME_ZONE, USE_I18N, USE_L10N, USE_TZ,
    REST_FRAMEWORK, SWAGGER_SETTINGS,
    MIDDLEWARE, SECRET_KEY, TEMPLATES, AUTH_PASSWORD_VALIDATORS
)
import os

MODE_ENVIROMENT = os.getenv("MODE_ENVIROMENT", "development")

ROOT_URLCONF = 'softeng.urls'
WSGI_APPLICATION = 'softeng.wsgi.application'
CORS_ORIGIN_ALLOW_ALL = True
ALLOWED_HOSTS = ['*']

if MODE_ENVIROMENT == 'development':
    DEBUG = True
    DATABASES = DEVELOPMENT_DB
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    INSTALLED_APPS = DEVELOPMENT_APPS

elif MODE_ENVIROMENT == 'production':
    DEBUG = False
    DATABASES = PRODUCTION_DB
    INSTALLED_APPS = PRODUCTION_APPS
