# Generated by Django 2.0.6 on 2018-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPARQLQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question to specific query.', max_length=100, verbose_name='Question')),
                ('query', models.TextField(help_text='SPARQL Query to get specific result from triplestore', verbose_name='Query')),
            ],
            options={
                'verbose_name': 'SPARQL Query',
                'verbose_name_plural': 'SPARQL Queries',
            },
        ),
    ]
